name: Execute Slack RPA

on:
  schedule:
    - cron: '0 * * * *' # Se ejecuta cada hora
  workflow_dispatch:   # Permite que t煤 le des al bot贸n "Run" manualmente

jobs:
  run-rpa:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANTE: Permite que el bot guarde los cambios en el JSON

    steps:
      - name: Checkout c贸digo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar RPA
        env:
          # Pasamos el secreto como variable de entorno
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          ID_SMOKE_CHANNEL: ${{ secrets.ID_SMOKE_CHANNEL }}
          ID_QA_CHANNEL: ${{ secrets.ID_QA_CHANNEL }}
        run: python slack_rpa.py

      - name: Guardar progreso (Persistencia)
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add rpa_state.json
          # Si el archivo cambi贸 (hubo rotaci贸n), hace commit y push
          git diff --quiet && git diff --staged --quiet || (git commit -m " RPA: Rotaci贸n de encargado" && git push)